### ISSUE TITLE
Hard dependency on Python 3.4

### ISSUE THREAD

**Issue by mruegenberg** [nicobou/shmdata#2]
Hi,
I just tried to build and install shmdata and got problems with a missing `python3.4-config`, since I only have Python 3.5.
Replacing `python3.4-config` with `python3-config` in `configure.ac` and `wrappers/python/Makefile.am` results in a successful build.

(I'm on Arch  Linux.)

**Comment by nicobou** [comment]
Thanks for your report, this has been corrected in the develop branch. This will be on master at next release.
